2025-08-05 11:09:38,393 - INFO - Starting bot...
2025-08-05 11:09:39,775 - INFO - Bot is ready.
2025-08-05 11:09:39,775 - INFO - Starting DP Ticket Automation - By Setiyo Aryo
2025-08-05 11:09:39,806 - INFO - Master data loaded successfully. Found 4540 entries.
2025-08-05 11:09:39,806 - INFO - Daily work list ready. Found 1 tickets.
2025-08-05 11:09:39,806 - INFO - Login attempt 1...
2025-08-05 11:10:17,584 - INFO - Login attempt 2...
2025-08-05 11:10:22,371 - INFO - Interrupt signal received, cleaning up...
2025-08-05 11:10:22,372 - INFO - Login attempt 3...
2025-08-05 11:10:22,374 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18e9e862c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f33e08cf910b21849bfd9ebb51fe03e0/url
2025-08-05 11:10:22,378 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18e9e86350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f33e08cf910b21849bfd9ebb51fe03e0/url
2025-08-05 11:10:22,382 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18e9e862f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f33e08cf910b21849bfd9ebb51fe03e0/url
2025-08-05 11:10:22,387 - ERROR - Login failed after multiple attempts
2025-08-05 11:10:22,390 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18e9e85fc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f33e08cf910b21849bfd9ebb51fe03e0
2025-08-05 11:10:22,392 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18e9e86bf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f33e08cf910b21849bfd9ebb51fe03e0
2025-08-05 11:10:22,398 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18e9e86d70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f33e08cf910b21849bfd9ebb51fe03e0
